Hello/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf  import  settings 
from django.conf.urls.static import static
# to change the default djnago admin text  we have added these 3 lines
admin.site.site_header = "GSSS Gokhra Admin"
admin.site.site_title = "GSSS Gokhra Admin Portal"
admin.site.index_title = "Welcome to GSSS Gokhra Researcher Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls'))
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from home import views

urlpatterns = [
  path("",views.index,name='home'),
  path("about",views.about,name='about'),
  path("contact",views.contact,name='contact'),
  path("service",views.service,name='service'),
  path("add",views.add, name="add"),
  path("staffadd/<catr>",views.staffadd,name='staffadd'),
  path("staff/<cat>",views.Staff,name='Staff'),
  path("masterentry",views.mentry,name='mentry'),
  path("updatetehsil",views.addedittehsil,name='updatetehsil'),
  path("updatepanch", views.addeditpanchyat,name='updatepanch'),
  path("updatedistt", views.addeditdistt,name='updatedistt'),
  path("updatesubject",views.addeditsubject,name="updatesubject"),
  path("updatebank",views.addeditbank,name="updatebank"),
  path("updatepo",views.addeditpo,name="updatepo"),
  path("updatestate",views.addeditstate,name="updatestate"),
  path('updateclssubj',views.subjmapp,name='updateclssubj'),
  path("studentreg",views.studentreg,name="studentreg")

  
]
urlpatterns =urlpatterns+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT )

home/models.py
from os import truncate
from random import choice, choices
from unittest.util import _MAX_LENGTH
from django.db import ProgrammingError, models
from django.db.models.deletion import CASCADE
from django.db.models.enums import Choices
from django.db.models.expressions import F
from django.db.models.fields.json import CaseInsensitiveMixin
from django.db.models.functions import Concat
from django.db.models import Max
from django.db.models.functions import Concat

import datetime
from datetime import datetime
from django.forms import CharField
from django.utils import timezone
# Create your models here.
class Destination:
    id: int
    name:str
    cls:int
    rno:int
    result:bool
class exammas(models.Model):
    exmtype=models.CharField(max_length=10)
    def __str__(self):
        return self.exmtype 

class schoolmas(models.Model):
    udise=models.IntegerField()
    schoolcoe=models.IntegerField()
    Schoolnm=models.CharField(max_length=50)
    schooladdress=models.CharField( max_length=50,default=False, blank=False)
    def __str__(self):
        return self.Schoolnm
class statemas(models.Model):
   statenm=models.CharField(max_length=20, blank=False, default=False)
   def __str__(self):
       return self.statenm
class disttmas(models.Model):
    scode=models.ForeignKey(statemas,on_delete=CASCADE)
    #disttcd=models.CharField(max_length=2,blank=False,default=False)
    disttnm=models.CharField(max_length=25,blank=False,default=False)
    def __str__(self):
            return self.disttnm
class tehmas(models.Model):
    stcod=models.ForeignKey(statemas,on_delete=CASCADE)
    disttcd=models.ForeignKey(disttmas,on_delete=CASCADE)
   # tehcd=models.CharField(max_length=2,blank=False,default=False)
    tehname=models.CharField(max_length=25,default=False, blank=False)
    def __str__(self):
            return self.tehname
class pomas(models.Model):
    pincd=models.IntegerField()
    ponmame=models.CharField(max_length=20, default=False,blank=False)
    distcd=models.ForeignKey(disttmas,on_delete=CASCADE)
    def __str__(self):
        return self.ponmame

class panchayatmas(models.Model):
    stcd=models.ForeignKey(statemas,on_delete=CASCADE)
    disttcd=models.ForeignKey(disttmas,on_delete=CASCADE)
    tehcd=models.ForeignKey(tehmas,on_delete=CASCADE)
    #pancd=models.CharField(max_length=2,default=False,blank=False)
    panname=models.CharField(max_length=20,default=False,blank=False)
    def __str__(self):
        return self.panname
class bankmas(models.Model):
    bankifsc=models.CharField(max_length=11, blank=False, default= False)
    bnkbranchnm=models.CharField(max_length=25,blank=False,default=False)
    def __str__(self):
        return self.bnkbranchnm
class classmas(models.Model):
    clevelchoices=(('E','Elementary'),('H','Higher'),('S','Secondary'))
    clasdesc=models.CharField(max_length=20, unique=True)
    classlvl=models.CharField(max_length=1,choices=clevelchoices,default='S')
    def __str__(self):
        return self.clasdesc
class subjmas(models.Model):
    sujcname=models.CharField(max_length=30)
    def __str__(self):
        return self.sujcname



class desigmas(models.Model):
    empcatchoices = (('T', 'Teaching Staff'), ('N', 'Non Teaching Staff'),('S','SMC'))
    desigcd=models.AutoField(primary_key=True)
    deisgnm=models.CharField( max_length=50)
    desgcat=models.CharField(max_length=1,choices=empcatchoices,default='T')


    def __str__(self):
        return self.deisgnm

class  staffmas(models.Model):
   
    empsexchoices=(('M','Male'),('F','Feamle'),('O','Other/लागू नहीं'))
    empcstchoices = (('G','General'),('O','OBC'),('S','SC'),('T','ST'),('N','Not Applicable'))
    empid=models.AutoField(primary_key =True)
    schoolcd=models.ForeignKey(schoolmas,on_delete=CASCADE)
    empname=models.CharField(max_length=50, blank=False,null=False)
    pmiscode=models.IntegerField()
    empdob=models.DateField()
    empdoj=models.DateField()
    empquali=models.CharField(max_length=50)
    empmob=models.IntegerField()
    emppic=models.ImageField(upload_to ='staffpic')
    empemail=models.EmailField()
    sntyno=models.IntegerField()
    empsex=models.CharField(max_length=1,choices=empsexchoices,default='M')
    empcst=models.CharField(max_length=1,choices=empcstchoices,default='G')
    designation = models.ForeignKey(desigmas, on_delete=CASCADE)
    subject=models.ForeignKey(subjmas, on_delete=CASCADE,null=True,blank=True)    

    def __str__(self):
        return  self.empname
class studentbasic(models.Model):
     stcatchoices = (('G','General'),('O','OBC'),('S','SC'),('T','ST'),('N','Not Applicable'),('H','General IRDP'),('I','OBC IRDP'),('J','SC IRDP'),('K','ST IRDP'))
     stsexchoices = (('M','Male'),('F','Feamle'),('O','Other'))
     streligionchoices = (('H','Hindu'),('M','Muslim'),('S','Sikh'),('C','Christian'))
     statuschoices=(('A','Admitted'),('E','Pending'),('L','SLC'))
     bldchoices=(('A','A+'),('A1','A-'),('B','B+'),('B1','B-'),('O','O+'),('O1','O-'),('AB','AB+'),('AB1','AB-'),('Z','Not Known'))
     stdname=models.CharField(max_length=25,blank=False,null=False)
     stfname=models.CharField(max_length=25,blank=False,null=False)
     stmname=models.CharField(max_length=25,blank=False,null=False)
     strelig=models.CharField(max_length=1,choices=streligionchoices,default='H')
     stcat=models.CharField(max_length=1,choices=stcatchoices,default='G')
     stsex=models.CharField(max_length=1,choices=stsexchoices,default='M')
     stdob=models.DateField()
     stblood=models.CharField(max_length=3,choices=bldchoices,default='Z')
     stdacct=models.IntegerField()
     stbank=models.ForeignKey(bankmas,on_delete=CASCADE)
     stdmob=models.IntegerField()
     stduid=models.IntegerField()
     stvillg=models.CharField(max_length=25,blank=False,null=False)
     stdistt=models.ForeignKey(disttmas,on_delete=CASCADE)
     Stteh=models.ForeignKey(tehmas,on_delete=CASCADE)
     stpo=models.ForeignKey(pomas,on_delete=CASCADE)
     stpanch=models.ForeignKey(panchayatmas,on_delete=CASCADE)
     stpic=models.ImageField(upload_to='staffpic', null=True)
     sthrtc=models.CharField(max_length=25,blank=True)
     stsatus=models.CharField(max_length=1,choices=statuschoices, default='E',blank=False)
     stdate=models.DateField(null=True)

     def __str__(self):
        return  self.stdname 
class studentclass (models.Model):
    resultchoice=(('P','Pass'),('F','Fail'),('L','SLC'),('A','Admitted'),('E','Pending'))
    school= models.ForeignKey(schoolmas,on_delete= CASCADE)
    classcd=models.ForeignKey(classmas,on_delete=CASCADE)
    adyear=models.CharField(max_length=4,null=True)
    admno=models.IntegerField(null=True)
    admdate=models.DateField(null=True)
    rollno=models.IntegerField(null=True)
    appid=models.ForeignKey(studentbasic,on_delete=CASCADE)
    appdate=models.DateField(null=True)
    sesyear=models.CharField(max_length=4)
    examrno=models.IntegerField()
    mo=models.IntegerField(default=0)
    mm=models.IntegerField(default=0)
    clstat=models.CharField(max_length=1,choices=resultchoice,default='E')
    def __str__(self):
        return (self.sesyear)
class studentsubj(models.Model):
    sujrslt=(('P','Pass'),('F','Fail'))
    stuclid=models.ForeignKey(studentclass,on_delete=CASCADE)
    examcd=models.ForeignKey(exammas,on_delete=CASCADE)
    subjcd=models.ForeignKey(subjmas,on_delete=CASCADE)
    tmo=models.IntegerField()
    amo=models.IntegerField()
    pmo=models.IntegerField()
    subjresult=models.CharField(max_length=1,choices=sujrslt,null=True)
    def __str__(self):
        return self.subjcd.sujcname
 
class classsubject(models.Model):
    clscd=models.ForeignKey(classmas,on_delete=CASCADE)
    subj=models.ForeignKey(subjmas,on_delete=CASCADE)
    tmm=models.IntegerField()
    pmm=models.IntegerField()
    amm=models.IntegerField()
    subjcombid=models.IntegerField()
    
    def __str__(self):
        return (self.clscd.clasdesc,self.subj.sujcname)

templates/Staff.html
{% extends 'base.html' %}
{% load static %}
{% static "Image" as baseUrl %}


 {% block title%}
     Teaching staff
  {% endblock %}
{% block body%}
<p> List of  {{ cattype.first.get_desgcat_display}}</p>
<table class="table table-dark table-striped">
    <thead>
      <tr>
        <th scope="col">Name of Employee</th>
        <th scope="col">Designation</th>
        <th scope="col"> Qualification</th>
        <th scope="col">PMIS</th>
        <th scope="col">Mobile</th>
        <th scope="col">Image</th>
      </tr>
    </thead>
    {%for staff in staff %}
    <tbody>
      <tr>
        <th scope="row">{{staff.empname}}</th>
       
        <td>
         
              {% if staff.subject.id == 11 %}
                  {{staff.designation}}
              {% else %}
                  {{staff.designation}} {{staff.subject}} 
              {% endif %}
          
          </td>
        <td>{{staff.empquali}}</td>
        <td>{{staff.pmiscode}}</td>
        <td>{{staff.empmob}}</td>
        <td>
            <img src="{{staff.emppic.url}}"  class="img-thumbnail" alt="..." height=100 width=150>
            
        </td>
      </tr>
     {% comment %}  <tr>
        <th scope="row">2</th>
        <td>Jacob</td>
        <td>Thornton</td>
        <td>@fat</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td colspan="2">Larry the Bird</td>
        <td>@twitter</td>
      </tr> {% endcomment %}
    </tbody>
    {% endfor %} 
  </table>


{% endblock body %}

templates/adddistt.html
{% extends 'base.html' %}
 {% block title%}
Master Entery
  {% endblock %}
{% block body%}

<h3> Update District </h3>
<form action="" method="post" id="initialform">
    {% if not disttselected %}
            <label class="label label-warning"> State - {{ stnm}} 

            </label>
                {% if dislist %}
                        <div class="form-group col-md-12">
                        <h4> <label class="label label-warning"> Already Added District </label> </h4>
                    </div>
                        <div class="container">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th scope="col"  >District Name </th>
                                    <th scope="col"  > Click to Edit </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for row in dislist %}
                                    <tr>
                                        <td scope="col"  > 
                                            {{ row.disttnm }}
                                        </td>
                                        <td scope="col"  > 
                                            <button type="submit" name = "edit" value = "{{ row.id }}">Edit</button>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="form-row">
                        <div class="form-group col-md-12">
                        <h3> <label class="label label-warning"> No District Available </label> </h3>
                        </div>
                    </div>
                {% endif %}
        <div class="form-row">
            <div class="form-group col-md-6">
            <button type="submit" name="addmore" class="btn btn-primary">Add District</button>
        </div>
            <div class="form-group col-md-6">
            <button type="submit" name="back" class="btn btn-primary">Back</button>
        </div>
           
    {% else %}
        <div class="form-row">
            <div class="form-group col-md-6">
            <label for="bid"> District Code </label>
            <input type='text' name = "dis" class="form-control" id="dis" value =  "{{ discd }}" readonly>
        </div>


        <div class="form-row">
            <div class="form-group col-md-6">
            <label for="aname">District  Name</label>
            <input type="text" class="form-control is-valid" name = "aname" id="aname" pattern="[A-Za-z\u0900-\u097F ()]{0,60}" value = "{{ disname }}" title="Maximum 60 Character Alphabets and Spaces only." placeholder="Tehsil Name" autofocus  required>
            </div>
        </div>
    <div class="form-row">
        <div class="form-group col-md-4">
        <button type="submit" name="save" class="btn btn-primary">Save</button>
    </div>
    <div class="form-group col-md-4">
        <button type="submit" name="cancel" class="btn btn-primary" formnovalidate>Cancel</button>
    </div>
</div>
{% endif %}
{% csrf_token %}

</form>
    <script type="text/javascript">
        function OnChange()
        {
                document.getElementById("initialform").submit();
        } 
    </script>




{% endblock body %}
    

templates/addeditbnkbrnch.html
{% extends 'base.html' %}
 {% block title%}
Master Entery
  {% endblock %}
{% block body%}
    <h3> Update Bank</h3>
    <form action="" method="post" id="initialform">
        {% if not bankselect %}
            {% if banklist %}
                <div class="form-group col-md-12">
                    <h4> <label class="label label-warning"> Already Added Bank Branch</label> </h4>
                </div>
                <div class="container">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th scope="col"  >Bank Branch Name </th>
                                        <th scope="col"  >IFSC CODE </th>
                                        <th scope="col"  > Click to Edit </th>
                                    </tr>
                                </thead>
                            <tbody>
                                {% for row in banklist %}
                                    <tr>
                                        <td scope="col"  > 
                                            {{ row.bnkbranchnm }}
                                        </td>
                                        <td scope="col"  > 
                                            {{ row.bankifsc }}
                                        </td>
                                        <td scope="col"  > 
                                            <button type="submit" name = "edit" value = "{{ row.id }}">Edit</button>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                </div>
            {% else %}
                <div class="form-row">
                    <div class="form-group col-md-12">
                    <h3> <label class="label label-warning"> No Bank Available </label> </h3>
                </div>
                </div>
            
            {% endif  %}
        <div class="form-row">
            <div class="form-group col-md-6">
                    <button type="submit" name="addmore" class="btn btn-primary">Add Bank</button>
            </div>
            <div class="form-group col-md-6">
                    <button type="submit" name="back" class="btn btn-primary">Back</button>
             </div>    
           
         {%else %}
         <div class="form-row">
            <div class="form-group col-md-6">
            <label for="bid"> Bank Code </label>
            <input type='text' name = "bankcd" class="form-control" id="bankcd" value =  "{{ bankcd }}" readonly>
        </div>


        <div class="form-row">
            <div class="form-group col-md-6">
            <label for="aname">Bank   Name</label>
            <input type="text" class="form-control is-valid" name = "bnkname" id="bnkname" pattern="[A-Za-z\u0900-\u097F ()]{0,60}" value = "{{ bnkname }}" title="Maximum 60 Character Alphabets and Spaces only." placeholder="Tehsil Name" autofocus  required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
            <label for="aname">IFSC CODE</label>
            <input type="text" class="form-control is-valid" name = "ifsc" id="ifsc" pattern="[A-Za-z0-9\u0900-\u097F ()]{0,60}" value = "{{ ifsc }}" title="Maximum 60 Character Alphabets and Spaces only." placeholder="Tehsil Name" autofocus  required>
            </div>
        </div>
    <div class="form-row">
        <div class="form-group col-md-4">
        <button type="submit" name="save" class="btn btn-primary">Save</button>
    </div>
    <div class="form-group col-md-4">
        <button type="submit" name="cancel" class="btn btn-primary" formnovalidate>Cancel</button>
    </div>
    </div>


        {% endif %}

        {% csrf_token %}       
    </form> 
    <script type="text/javascript">
        function OnChange()
        {
                document.getElementById("initialform").submit();
        } 
    </script>    
{% endblock body  %}

templates/addeditstate.html
{% extends 'base.html' %}
 {% block title%}
State 
  {% endblock %}
{% block body%}
    <h3> Update Subject</h3>
    <form action="" method="post" id="initialform">
        {% if not stselect %}
                {%if stlist %}
                    <div class="form-group col-md-12">
                        <h4> <label class="label label-warning"> Already Added Subject</label> </h4>
                    </div>
                    <div class="container">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th scope="col"  >State Name </th>
                                            <th scope="col"  > Click to Edit </th>
                                        </tr>
                                    </thead>
                                <tbody>
                                    {% for row in stlist %}
                                        <tr>
                                            <td scope="col"  > 
                                                {{ row.statenm }}
                                            </td>
                                            <td scope="col"  > 
                                                <button type="submit" name = "edit" value = "{{ row.id }}">Edit</button>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                    </div>
                {% else %}
                    <div class="form-row">
                        <div class="form-group col-md-12">
                        <h3> <label class="label label-warning"> No Subject Available </label> </h3>
                    </div>
                    </div>
                
                {% endif  %}
        <div class="form-row">
                <div class="form-group col-md-6">
                    <button type="submit" name="addmore" class="btn btn-primary">Add State</button>
                </div>
                <div class="form-group col-md-6">
                    <button type="submit" name="back" class="btn btn-primary">Back</button>
                </div>
    {% else %}
        <div class="form-row">
            <div class="form-group col-md-6">
            <label for="bid"> State Code </label>
            <input type='text' name = "stcd" class="form-control" id="stcd" value =  "{{ stcd }}" readonly>
        </div>


        <div class="form-row">
            <div class="form-group col-md-6">
            <label for="aname">State  Name</label>
            <input type="text" class="form-control is-valid" name = "stname" id="stname" pattern="[A-Za-z\u0900-\u097F ()]{0,60}" value = "{{ stname }}" title="Maximum 60 Character Alphabets and Spaces only." placeholder="State Name" autofocus  required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <button type="submit" name="save" class="btn btn-primary">Save</button>
            </div>
            <div class="form-group col-md-4">
                <button type="submit" name="cancel" class="btn btn-primary" formnovalidate>Cancel</button>
            </div>
        </div>
    {% endif %}
    

{% csrf_token %}       
</form> 
<script type="text/javascript">
function OnChange()
{
        document.getElementById("initialform").submit();
} 
</script>    
{% endblock body  %}

templates/contact.html
{% extends 'base.html' %}
 {% block title%}
 Contact
  {% endblock %}
{% block body%}
This is Contact
{% endblock body %}

templates/service.html
{% extends 'base.html' %}
 {% block title%}
 Service
  {% endblock %}
{% block body%}
This is service
{% endblock body %}

templates/staffadd.html
{% extends 'base.html' %}
{% load static %}
{% static "Image" as baseUrl %}


 {% block title%}
     Teaching staff
  {% endblock %}
{% block body%}
<div class="p-3 mb-2 bg-warning text-white">
<p ><b> Registration of  {{ catlist.first.get_desgcat_display}}</b></p></div>
<div class="p-3 mb-2 bg-info text-white">
<div class="ms-5">
  <form action="" method="post" id="staffreg" name="staffreg" class="row g-3" enctype="multipart/form-data">
    {% csrf_token %}
    
   
    <br>
     
      <div class="center" style="text-align: center;" >
            <div class="center" style="width: 500px; margin: 0 auto;" style="text-align: center;">
              {% comment %} <p class="text-success"> {% endcomment %}
                <b>विद्यालय परिवार सदस्यों का पंजीकरण प्रपत्र/Registration Form.</b>
              {% comment %} </p> {% endcomment %}

            </div>
         <br>
      </div>
  <div class="row mb-3">
        
          <div class="form-group col-md-4">
            <label for="inputState">Name</label>
              <input type="text" class="form-control" id="emp" name ="emp" placeholder="Name/नाम" required=True>
          </div>
          {% comment %} <div class="form-group col-md-4">
              <label for="inputState">Teaching/Non Teaching/SMC</label>
          
              {% comment %} <select id="entfr" class="form-control">
                <option selected>Choose...</option>
                {% for x,y in catlist %}
                                
                  <option value = {{ x }}>{{ y }}</option>
                              
                {% endfor %}
              </select> 
            </div> {% endcomment %}
          <div class="form-group col-md-4">
              <label for="inputState">Upload Image </lable>
              <input class="form-control" type="file" id="pic" name="pic">
            </div>
          <div class="form-group col-md-4">
                <label for="inputState">Designation</label>
                <select id="desg" name="desg"class="form-control">
                <option selected>Choose Designation</option>
              {% for entry in desglist %}
                                
                <option value = {{ entry.desigcd }}>{{ entry.deisgnm }}</option>
                                
              {% endfor %}
            </select>
        </div>
    </div>
      <div class="form-group col-md-4">
        <label for="Gender">Gender</label>
        <select id="gend" name="gend" class="form-control">
          <option selected>Choose...</option>
          {% for x,y in sex %}
                                
          <option value = {{ x }}>{{ y }}</option>
                              
          {% endfor %}
        </select>
      </div>
      <div class="form-group col-md-4">
        
        <label for="subj">Role/Subject</label>
        {% comment %} {% if catr != 'T' %}
        <select id="subj" name="subj" class="form-control">
          <option value = 11 selected>Not Applicable</option>
         
        </select>
      
        {% else %} {% endcomment %}
          <select id="subj" name="subj" class="form-control" required>
          <option selected>Choose...</option>
          
            {% for entry in subjlist %}
                                
            <option value = {{ entry.id }}>{{ entry.sujcname }}</option>
                                
            {% endfor %}
         
        </select>
        {% comment %} {% endif %} {% endcomment %}

      </div>
      <div class="form-group col-md-4">
        <label for="inputState">Category</label>
        <select id="ecat" name="ecat" class="form-control">
          <option selected>Choose...</option>
          {% for x,y in cstlist %}
                                
          <option value = {{ x }}>{{ y }}</option>
                              
          {% endfor %}
        </select>
      </div>
      <div class="form-group col-md-4">
        <label for="dob">Date of Birth </label>
         <input type='date' class="form-control" id='dob' name='dob' />
      </div>
      <div class="form-group col-md-4">
        <label for="doj">Date of Joining </label>
         <input type='date' class="form-control" id='doj' name='doj' />
      </div>
      {% comment %} <div class="container">
        <div class="row">
           <div class='col-sm-6'>
              <div class="form-group">
                 <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" id='datetimepicker1'/>
                    <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                 </div>
              </div>
           </div>
                <script type="text/javascript">
                  $(function () 
                {
                  $('#datetimepicker1').datetimepicker();
               });
              </script>
        </div>
     </div> {% endcomment %}
      <div class="form-group col-md-4">
        <label for="inputPassword4">PMIS Code </label>
        <input type="text" class="form-control" id="pmis" name="pmis" placeholder="PMIS CODE ">
      </div>
      <div class="form-group col-md-4">
        <label for="inputPassword4">MOBILE NUMBER </label>
        <input type="text" class="form-control" id="mob" name="mob"  placeholder="Mobile Number">
      </div>
      <div class="form-group col-md-4">
        <label for="inputPassword4">Email </label>
        <input type="text" class="form-control" id="email" name="email"  placeholder="Email">
      </div>
      <div class="form-group col-md-4">
        <label for="inputPassword4">Qualification </label>
        <input type="text" class="form-control" id="qua" name ="qua" placeholder="Qualification">
      </div>
      <div class="form-group col-md-4">
        <label for="inputPassword4">Seniority Number </label>
        <input type="text" class="form-control" id="seno" name="seno" placeholder="Seniority Number">
      </div>
    </div>
    {% comment %} <div class="form-group">
      <label for="inputAddress">Address</label>
      <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
    </div>
    <div class="form-group">
      <label for="inputAddress2">Address 2</label>
      <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputCity">City</label>
        <input type="text" class="form-control" id="inputCity">
      </div>
      <div class="form-group col-md-4">
        <label for="inputState">State</label>
        <select id="inputState" class="form-control">
          <option selected>Choose...</option>
          <option>...</option>
        </select>
      </div>
      <div class="form-group col-md-2">
        <label for="inputZip">Zip</label>
        <input type="text" class="form-control" id="inputZip">
      </div>
    </div>
    <div class="form-group">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="gridCheck">
        <label class="form-check-label" for="gridCheck">
          Check me out
        </label>
      </div>
    </div> {% endcomment %}
    <div class="mx-auto"style="width: 500px;">
      <br>
        <button type="submit" class="btn btn-primary" id="save" name="save">Submit</button>
   
  </form>
</div>
</div>
</div>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

  {% if submitted %}
  <script>
      alert("Saved Successfully");
      
    </script>
  {% endif %}
 

  {% endblock body %}